use JXGL;
CREATE TABLE S
	(S#          CHAR(9)       PRIMARY KEY,
	SNAME        CHAR (10)     NOT NULL,
	SSEX         CHAR(2)       CHECK(SSEX IN ('ÄÐ','Å®')),
	SBIRTHIN     DATETIME      NOT NULL,
	PLACEOFB     CHAR(16),
	SCODE#       CHAR(5)       NOT NULL,
	CLASS        CHAR(6)       NOT NULL);

CREATE TABLE SC
		(S# CHAR(9),
		 C# CHAR(7),
		 GRADE INT,
		 PRIMARY KEY (S#,C#),
		 CHECK(GRADE BETWEEN 0 AND 100));

CREATE TABLE SS
(SCODE# CHAR(5),
 SSNAME CHAR(20));

CREATE TABLE C
( C# CHAR(7),
  CNAME CHAR(20),
  CLASSH INT) ;

CREATE TABLE CS
( SCODE# CHAR(5),
  C# CHAR(7));

CREATE TABLE T
( T# CHAR(8),
  TNAME CHAR(16),
  TSEX CHAR(2),
  TBIRTHIN DATETIME,
  TITLEOF CHAR(10),
  TRSECTION CHAR(16),
  TEL CHAR(11));

CREATE TABLE TEACH
( T# CHAR(8),
  C# CHAR(7));